"use client";

import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import { NeynarAuthButton, useNeynarContext } from "@neynar/react";
import axios, { AxiosError } from "axios";
import Image from "next/image";

interface ErrorRes {
  message: string;
}

interface Cast {
  object: string;
  hash: string;
  author: any;
  text: string;
  timestamp: string;
  reactions: any;
  replies: any;
}

interface ScoreData {
  casts: Cast[];
}

const Home: NextPage = () => {
  const { user } = useNeynarContext();
  const [text, setText] = useState("");
  const [userCasts, setUserCasts] = useState<Cast[]>([]);

  const handlePublishCast = async () => {
    try {
      await axios.post<{ message: string }>("/api/cast", {
        signerUuid: user?.signer_uuid,
        text,
      });
      alert("Cast Published!");

      setText("");
      fetchScore(); // Refresh casts after publishing
    } catch (err) {
      const { message } = (err as AxiosError).response?.data as ErrorRes;
      alert(message);
    }
  };

  const fetchScore = async () => {
    if (user) {
      try {
        const response = await axios.post<{
          message: string;
          data: { casts: Cast[] };
        }>("/api/getScore", {
          fid: user?.fid,
        });
        console.log(response.data.data);
        if (response.data.data && response.data.data.casts) {
          setUserCasts(response.data.data.casts);
        }
      } catch (error) {
        console.error("Error fetching casts:", error);
      }
    }
  };

  useEffect(() => {
    fetchScore();
  }, [user]);

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleString();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App with Farcaster</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <div style={{ marginTop: "2rem" }}>
          <NeynarAuthButton />

          {user && (
            <div
              className="flex flex-col gap-4 w-96 p-4 rounded-md shadow-md"
              style={{ marginTop: "1rem" }}
            >
              <div className="flex items-center gap-4">
                {user.pfp_url && (
                  <img
                    src={user.pfp_url}
                    width={40}
                    height={40}
                    alt="User Profile Picture"
                    className="rounded-full"
                  />
                )}
                <p className="text-lg font-semibold">{user?.display_name}</p>
              </div>
              <textarea
                value={text}
                onChange={(e) => setText(e.target.value)}
                placeholder="Say Something"
                rows={5}
                className="w-full p-2 rounded-md shadow-md text-black placeholder:text-gray-900"
                style={{
                  width: "100%",
                  padding: "0.5rem",
                  borderRadius: "0.375rem",
                  boxShadow: "0 1px 3px 0 rgba(0, 0, 0, 0.1)",
                }}
              />
              <button
                onClick={handlePublishCast}
                className="mt-4 px-4 py-2 bg-blue-500 text-white rounded-md shadow-md hover:bg-blue-600 transition-colors duration-200 ease-in-out"
                style={{
                  marginTop: "1rem",
                  padding: "0.5rem 1rem",
                  backgroundColor: "#3b82f6",
                  color: "white",
                  borderRadius: "0.375rem",
                  boxShadow: "0 1px 3px 0 rgba(0, 0, 0, 0.1)",
                }}
              >
                Cast
              </button>
            </div>
          )}

          {userCasts.length > 0 && (
            <div className="mt-8 w-full max-w-2xl">
              <h2 className="text-xl font-bold mb-4">Your Recent Casts</h2>
              <div className="space-y-4">
                {userCasts.map((cast) => (
                  <div
                    key={cast.hash}
                    className="p-4 border rounded-lg shadow-sm"
                  >
                    <div className="flex items-center gap-2 mb-2">
                      {cast.author && cast.author.pfp_url && (
                        <img
                          src={cast.author.pfp_url}
                          width={32}
                          height={32}
                          alt="Author"
                          className="rounded-full"
                        />
                      )}
                      <span className="font-medium">
                        {cast.author?.display_name || "User"}
                      </span>
                      <span className="text-gray-500 text-sm ml-auto">
                        {formatDate(cast.timestamp)}
                      </span>
                    </div>
                    <p className="text-gray-800">{cast.text}</p>
                    <div className="flex mt-2 text-sm text-gray-500">
                      <span className="mr-4">
                        ❤️ {cast.reactions?.likes_count || 0}
                      </span>
                      <span>💬 {cast.replies?.count || 0}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
