version: "3.8"

services:
  bot:
    build: .
    container_name: locol-ai-bot
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
    networks:
      - bot-network
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: locol-mongodb
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  mongodb_data:
